### ISSUE TITLE
[BetterChatNames] Doesn't work on Canary on v1.4.5

### ISSUE THREAD

**Issue by maenDisease** [Break-Ben/BetterDiscordAddons#13]
Plugin does nothing when enabled on canary
![image](https://user-images.githubusercontent.com/90428263/226727259-53eb3da5-2f55-4f75-b01a-52fb3d34dd2e.png)

Works on stable but sends this console error
![image](https://user-images.githubusercontent.com/90428263/226727300-cb67cdbf-6b89-43e3-9200-a6aee72899aa.png)

**Comment by Break-Ben** [comment]
Should be fixed in c578a22 (1.4.6), although let me know if it's not for you (I have tested it on normal and canary)
