### ISSUE TITLE
Does Not Work

### ISSUE THREAD

**Issue by Capy369** [Break-Ben/BetterDiscordAddons#14]
![Screenshot 2023-03-25 183415](https://user-images.githubusercontent.com/128597097/227712035-d128a477-910d-49ae-9283-4925f7ab5034.png)
It doesn't matter whether the theme is on or off, it doesn't work

**Comment by Break-Ben** [comment]
Are you on all of the latest versions (BetterDiscord 1.9.1 and BetterChatNames 1.4.6)?

**Comment by Capy369** [comment]
thanks

**Comment by Break-Ben** [comment]
I'm gonna assume that means there was no issue
