### ISSUE TITLE
BetterChatNames No longer functioning

### ISSUE THREAD

**Issue by BaconCatBug** [Break-Ben/BetterDiscordAddons#24]
it looks like the Discord update has broken this plugin. I've updated the ZeresPluginLibrary to the new working 2.0.19 but it seems like some form of element change has broken the BetterChatNames plugin
![image](https://github.com/Break-Ben/BetterDiscordAddons/assets/4897163/e1d6bf30-59c4-4478-ab00-eb151692d308)
![image](https://github.com/Break-Ben/BetterDiscordAddons/assets/4897163/fb083c97-2b32-403f-909a-943ae1790d19)

**Comment by Break-Ben** [comment]
Thanks for the report, it is a known issue that the plugin no longer works after the recent discord update (as well as many other plugins). I'm not sure when I will have time to fix it as I am busy with my final exams currently, but it should at least be fixed within 2 weeks from now. _(Also my plugin doesn't use ZeresPluginLibrary, so updating that plugin shouldn't affect mine)_

**Comment by Break-Ben** [comment]
Fixed in f323e8f (1.5.6)
Apologies for taking this long to fix it, I was even busier than I thought

**Comment by BaconCatBug** [comment]
No problem mate, thank you for taking the time to fix it.
