### ISSUE TITLE
BetterChatNames is no longer working.

### ISSUE THREAD

**Issue by nicktolman** [Break-Ben/BetterDiscordAddons#25]
I've updated both BetterDiscord and all my plugins and BetterChatNames no longer works. I just updated everything a minute ago.

**Comment by Break-Ben** [comment]
Please check other open/pinned issues before posting an issue, it has already been fixed in f323e8f (1.5.6) which has not yet been approved by the BD team. You can either wait for it to be approved or update the plugin file manually
