### ISSUE TITLE
Names not being changed in BD 1.10.2

### ISSUE THREAD

**Issue by ffuentesm** [Break-Ben/BetterDiscordAddons#28]
The channel list names are not being changed in the new BD update.
BetterChatNamesv1.6.0
![image](https://github.com/Break-Ben/BetterDiscordAddons/assets/44974827/d017c03d-93fa-4dfa-8b36-54d5c4633d5a)
![image](https://github.com/Break-Ben/BetterDiscordAddons/assets/44974827/3932bc7d-e1c2-4088-974c-6232c54490dc)

**Comment by Break-Ben** [comment]
Thanks for the report,
Fixed in 015061b (1.6.1)
