### ISSUE TITLE
Offshoot of  Names not being changed in BD 1.10.2 #28 by user FFuentesm

### ISSUE THREAD

**Issue by Thubbe42** [Break-Ben/BetterDiscordAddons#29]
Hey, as previously reported channel names aren't being changed in version 1.6.0. A previous issue about this has been closed with the reason of it being fixed in 1.6.1. But 1.6.1 doesn't seem to be currently accesible.

**Comment by Thubbe42** [comment]
As 1.6.1 is now avalible I will close

**Comment by Thubbe42** [comment]
As version 1.6.1 is now avalible I will close this issue.

**Comment by Break-Ben** [comment]
1.6.1 was already accessible via GitHub. It was not available directly within BD at the time of your report as it had not yet gone through the manual update approval process that I have no control over
