### ISSUE TITLE
Add option to remove emojis in chat names

### ISSUE THREAD

**Issue by DotBow** [Break-Ben/BetterDiscordAddons#31]
Using this regex it is possible to remove emojis from chat names.

https://stackoverflow.com/a/67705964

**Comment by Break-Ben** [comment]
Apologies for the late reply, I've been quite busy and honestly I've stopped using BD about a year ago,

Option added in b62a105 (1.6.3)
Note that it's disabled by default but you can enable it by setting `removeEmojis` to `true` on line 15
