### ISSUE TITLE
Apostrophe S ('s) is shown as capital "S" instead of lower case

### ISSUE THREAD

**Issue by ThatBurgundy** [Break-Ben/BetterDiscordAddons#8]
Apostrophe "S" ('s) is shown as capital 'S instead of lower case 's.

Example should read as "Oli's":
![image](https://user-images.githubusercontent.com/25126483/189618413-216fa9e0-183f-4eb4-91eb-e31adf71afc5.png)

**Comment by ThatBurgundy** [comment]
I copied the updated line into BD and it didn't change anything? I assume I just need to wait for the update to be pushed through BD?

**Comment by Break-Ben** [comment]
Oh okay, I'm assuming that name wasn't from a text channel, does this updated line (line 19) fix your issue?
`const CapitalRegex = new RegExp(/(^\w)|([^a-zA-ZÀ-ɏḀ-ỿ'’]\w)/g)`

**Comment by ThatBurgundy** [comment]
Yeah sorry should have mentioned it being a voice channel, I don't seem to be able to add apostrophes to text channel names, but yes that updated line fixed the issue. 

Thank you so much, honestly don't know how I could look at discord again without your plug-in. Something I never knew I needed and now couldn't live without <3

**Comment by Break-Ben** [comment]
Alright, thanks for the help, I now pushed the fix to bcc1a51 (1.3.6). Also thanks, I'm glad you like the plugin!
